[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/openai"
  to = "/.netlify/functions/openai"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["openai"]
  directory = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173